"""
Compatibility re-export module.

auth.py and api/dependencies.py import from app.utils.exceptions.
All exceptions live in app.utils.errors; this file re-exports them.
"""

from app.utils.errors import (
    ApplicationException,
    AuthenticationException,
    AuthorizationException,
    CacheConnectionError,
    CacheException,
    DatabaseConnectionError,
    DatabaseException,
    DocumentException,
    DocumentNotFound,
    DuplicateUserException,
    EmbeddingException,
    EmbeddingGenerationFailed,
    FileTooLarge,
    InvalidCredentialsException,
    InvalidFileType,
    InvalidQueryException,
    InvalidTokenException,
    LLMAPIError,
    LLMException,
    LLMResponseError,
    NotFound,
    PDFProcessingError,
    RateLimitException,
    TokenExpiredException,
    TokenMissingException,
    UserNotFoundException,
    ValidationError,
    ValidationException,
    VectorDBError,
)

__all__ = [
    "ApplicationException",
    "AuthenticationException",
    "InvalidCredentialsException",
    "TokenExpiredException",
    "InvalidTokenException",
    "TokenMissingException",
    "AuthorizationException",
    "UserNotFoundException",
    "DuplicateUserException",
    "DocumentException",
    "DocumentNotFound",
    "InvalidFileType",
    "FileTooLarge",
    "PDFProcessingError",
    "EmbeddingException",
    "EmbeddingGenerationFailed",
    "VectorDBError",
    "LLMException",
    "LLMAPIError",
    "LLMResponseError",
    "ValidationException",
    "InvalidQueryException",
    "RateLimitException",
    "DatabaseException",
    "DatabaseConnectionError",
    "CacheException",
    "CacheConnectionError",
    "NotFound",
    "ValidationError",
]
